spring:
  profiles:
    active: default
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/shopdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  security:
    jwt:
      secret: my-secret-keyfjfqofkopwfkofoefjefleflwsmlmsfsfnef
      access-token-expiration: 900000
      refresh-token-expiration: 604800000
    uuid:
      token-expiration: 60000
#      token-expiration: 3600000
logging:
  level:
    org.springframework.security: trace
