spring:
  profiles:
    active: default
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/shopdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirectUri: ${OAUTH2_REDIRECT_URI_REMOTE:${OAUTH2_REDIRECT_URI_LOCAL}}/google
          yandex:
            provider: yandex
            clientId: ${YANDEX_CLIENT_ID}
            clientSecret: ${YANDEX_CLIENT_SECRET}
            redirect-uri: ${OAUTH2_REDIRECT_URI_REMOTE:${OAUTH2_REDIRECT_URI_LOCAL}}/yandex
            authorizationGrantType: authorization_code
            clientName: Yandex

        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-name-attribute: default_email
            userInfoUri: https://login.yandex.ru/info

app:
  security:
    jwt:
      secret: ${JWT_SECRET}
      access-token-expiration: 900000
      refresh-token-expiration: 604800000
    uuid:
      token-expiration: 60000
#      token-expiration: 3600000
logging:
  level:
    org.springframework.security: trace
